#
# Copyright (C) 2022 DANS - Data Archiving and Networked Services (info@dans.knaw.nl)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

site_name: dans-datastation-architecture
theme:
  name: readthedocs

repo_name: DANS-KNAW/dans-datastation-architecture
repo_url: https://github.com/DANS-KNAW/dans-datastation-architecture

nav:
  - Core Services: index.md
  - Data Station: datastation.md
  - Vault as a service: vaas.md
  - DataverseNL: dataversenl.md
  - Deposit directory: deposit-directory.md
  - Mirroring to EASY: easy-mirror.md
  - Development: dev.md
  - Build status: status.md

plugins:
  - markdownextradata
  - search

extra:
  dataverse_org: https://dataverse.org/
  ds_archaeology: https://archaeology.datastations.nl/
  ds_ssh: https://ssh.datastations.nl/
  skosmos_url: https://skosmos.org/
  dans_bagit_profile: https://dans-knaw.github.io/dans-bagit-profile/versions/1.0.0/

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: False
      use_pygments: False
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
